### PR TITLE
Feature: @Json annotations

### PR DESCRIPTION
**Pull request by brain-diminished**
Add annotations `@JsonSkip`, `@JsonInclude`, `@JsonFormat` for more control over generated method `jsonSerialize()` in beans.

### CODE REVIEW

**Comment by moufmouf** [comment]
Hi Dorian!

Excellent idea!!! There is a small issue with PHPStan. Could you check it in CI?

**Comment by brain-diminished** [comment]
Hi David!
That one was kind of weird: PHPStan doesn't care about a `object !== null` expression, but he grunts about a `if (object === null)`. I updated the PHPDoc at 0a5f3fd, that should do the trick!

**Comment by brain-diminished** [comment]
I'm marking this PR as "wip", as I'm also thinking about a `@JsonCollection` annotation, that could be really useful (skip in `ObjectBeanPropertyDescriptor:getJsonSerializeCode`, and include collection in `DirectForeignKeyMethodDescriptor:getJsonSerializeCode`)

**Comment by brain-diminished** [comment]
PHPStan is up to no good... He's getting obnoxious about this generated line (`jsonSerialize` using `@JsonFormat` annotation):
```php
$array['weight'] = ($value = $this->getWeight()) !== null ? number_format($value, 2) . 'g' : null;
```
He won't trust that `number_format` is safely invoked, ie `$value !== null`... I'm pretty sure this is his mistake and not mine.

Everything else is in order, I believe new features are pretty neat... I remove the `wip` tag!

**Comment by brain-diminished** [comment]
So, final annotations are following:
- `@JsonKey(key=string)`
- `@JsonIgnore`
- `@JsonInclude`
- `@JsonRecursive`
- `@JsonCollection(key=string)`
- `@JsonFormat(datetime=string | decimals=int,point=string,separator=string,unit=string | property=string | method=string)`

For more information, documentation has been fully updated!

**Comment by moufmouf** [comment]
Hey Dorian,

Absolutely excellent! :100: 

I'll just check this PHPStan non-sense and merge this when PHPStan passes.

**Comment by moufmouf** [comment]
Ok, this is a bug in PHPStan that is getting confused with the inline assignment.

If I put the assignment on 2 lines, it is working.

I simply removed the assignment and made 2 calls to the getter. This is less optimal, but the getter is quite fast to call anyway.

**Comment by moufmouf** [comment]
By the way! I'm more and more relying on GraphQL for the API. As a direct result, I have no need for JSON serialization, which is cool :)

You might want to check GraphQLite http://graphqlite.thecodingmachine.io/, especially since there is a TDBM plugin to work with it: https://thecodingmachine.github.io/tdbm/doc/graphqlite.html

**Comment by brain-diminished** [comment]
Nice, thanks a lot.
I'll make sure to check GraphQL soon, I've been missing out for too long!
Cheers

**Pull request merged**
