### PR TITLE
Fix row from object storage can be null

### PR DESCRIPTION
**Pull request by rbergDrox**
$dbRow->getTDBMObject() with $dbRow can be null

### CODE REVIEW

**Comment by moufmouf** [comment]
This is weird... Look at the 2 lines:

```
if ($this->objectStorage->has($mainBeanTableName, $hash)) {
    $dbRow = $this->objectStorage->get($mainBeanTableName, $hash);
```

we call "has", then "get".

If "has" return true, then "get" should not return null.
If this happens, then there is a problem in the ObjectStorage implementation.

So I'd prefer you to have a look at what is going on in the objectstorage rather than trying to patch this in the classes consuming the ObjectStorage.

Hint: there are 2 classes implementing the ObjectStorageInterface: one using Weakref and one without Weakref... I think we use the one with Weakref

**Comment by Zheness** [comment]
Hello,

Yes it's weird, but `has()` returns `true` and `get()` returns `null` for me too.

I prefer to use this code, instead of the current PR:

```php
$bean = null;
if ($this->objectStorage->has($mainBeanTableName, $hash)) {
    $dbRow = $this->objectStorage->get($mainBeanTableName, $hash);
    if ($dbRow) {
        $bean = $dbRow->getTDBMObject();
    }
}
if ($bean === null) {
    // Let's construct the bean
    if (!isset($reflectionClassCache[$actualClassName])) {
        $reflectionClassCache[$actualClassName] = new \ReflectionClass($actualClassName);
    }
    // Let's bypass the constructor when creating the bean!
    $bean = $reflectionClassCache[$actualClassName]->newInstanceWithoutConstructor();
    $bean->_constructFromData($beanData, $this->tdbmService);
}
```

So if $dbRow is null, the $bean is still created after.

**Comment by moufmouf** [comment]
Ok, looking at it carefully, I now understand what is going on.

The problem stems from Weakref extension.

Between the 2 lines below, the garbage collector is triggered.

```php
if ($this->objectStorage->has($mainBeanTableName, $hash)) {
    $dbRow = $this->objectStorage->get($mainBeanTableName, $hash);
```

`has` and `get` call the "valid()" method of Weakref: https://github.com/thecodingmachine/tdbm/blob/master/src/WeakrefObjectStorage.php#L80

But the `valid()` method returns true the first time and false the second time.
This is completely counterintuitive.

Actually, any call to `valid()` is useless since the garbage collector could be triggered at any point in time before the call to `get()`. We should only rely on `get()` to decide whether a value is available or not!

**Comment by moufmouf** [comment]
Fixed by #82.
https://github.com/thecodingmachine/tdbm/releases/tag/v5.0.9

**Pull request closed without merging**
